### PR TITLE
PF-2665: Update CODEOWNERS file in P2 repositories

### PR DESCRIPTION
**Pull request by sjaca101**
When this PR is merged, it'll include:

- Update CODEOWNERS file:
  - @javier-cervantes-3pillarglobal @rubenmezar & @aviquez-3pillar as full approvers
  - @3rickgamez as source reviewer
  - @javier-cervantes-3pillarglobal as operations reviewer

Thanks!

### CODE REVIEW

**Review by 3rickgamez — DISMISSED** [review]
🍻

**Review by rubenmezar — COMMENTED** [review]
yarn build is failing

**Review by jorgemacias3pg — DISMISSED** [review]

**Review by jonathan-3pillar — APPROVED** [review]

**Review by aviquez-3pillar — DISMISSED** [review]

**Review by allangallo — DISMISSED** [review]

**Review by abarena — APPROVED** [review]
LGTM 👍🏼

**Comment by sjaca101** [comment]
Deprecated PR.

**Pull request closed without merging**
